CREATE TABLE `responseMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`chatMessageId` int NOT NULL,
	`userId` int,
	`userMessage` text NOT NULL,
	`response` text NOT NULL,
	`isDuplicate` boolean NOT NULL DEFAULT false,
	`duplicateSimilarity` decimal(5,4) DEFAULT '0',
	`isComplete` boolean NOT NULL DEFAULT true,
	`completenessScore` decimal(5,4) DEFAULT '1',
	`completenessIssues` text,
	`isFocused` boolean NOT NULL DEFAULT true,
	`focusScore` decimal(5,4) DEFAULT '1',
	`focusIssues` text,
	`isValid` boolean NOT NULL DEFAULT true,
	`qualityIssues` text,
	`qualityWarnings` text,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `responseMetrics_id` PRIMARY KEY(`id`)
);
