CREATE TABLE `staticSignatures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`carrierlockId` int,
	`readingId` varchar(128) NOT NULL,
	`birthDate` varchar(32) NOT NULL,
	`birthTime` varchar(32) NOT NULL,
	`birthCity` varchar(255) NOT NULL,
	`birthCountry` varchar(255) NOT NULL,
	`latitude` double NOT NULL,
	`longitude` double NOT NULL,
	`timezoneId` varchar(128),
	`timezoneOffset` double,
	`primeStack` text,
	`ninecenters` text,
	`fractalRole` varchar(128),
	`authorityNode` varchar(128),
	`vrcType` varchar(128),
	`vrcAuthority` varchar(128),
	`circuitLinks` text,
	`baseCoherence` int,
	`coherenceTrajectory` text,
	`microCorrections` text,
	`ephemerisData` text,
	`houses` text,
	`diagnosticTransmission` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `staticSignatures_id` PRIMARY KEY(`id`),
	CONSTRAINT `staticSignatures_readingId_unique` UNIQUE(`readingId`)
);
