/**
 * Probe: generate today's signal, and the same day forced to a low
 * clarity, so the two can be read side by side.
 *
 * Read-only. Writes nothing to the database. Run:
 *   npx tsx scripts/daily-signal-probe.ts
 */
// Must precede the env module — ENV is read at import time.
import "dotenv/config";
import { invokeLLM } from "../server/_core/llm";
import { frameFor, statusFor, registerFor } from "../shared/daily-signal";
import {
  buildSignalPrompt,
  assembleBody,
  type GeneratedSignal,
} from "../shared/daily-signal-prompt";

async function generate(frame: ReturnType<typeof frameFor>) {
  // invokeLLM carries the configured fallback chain, so a dead key on
  // one provider drops through to the next rather than failing.
  const res = await invokeLLM({
    temperature: 0.85,
    maxTokens: 900,
    messages: [{ role: "user", content: buildSignalPrompt(frame) }],
    responseFormat: { type: "json_object" },
  });

  const raw = res.choices?.[0]?.message?.content;
  const text = typeof raw === "string" ? raw : JSON.stringify(raw);
  const body = text.replace(/^```(?:json)?\s*|\s*```$/g, "").trim();
  console.log(`   [generated by ${res.model}]`);
  return JSON.parse(body) as GeneratedSignal;
}

function render(frame: ReturnType<typeof frameFor>, gen: GeneratedSignal) {
  const lines = assembleBody(frame, gen);
  console.log("\n" + "═".repeat(72));
  console.log(`${gen.title}  //  ${frame.status}  //  ${frame.clarity}%`);
  console.log("─".repeat(72));
  console.log(`⦿ TX ID: ${frame.txGenId}`);
  console.log(`Field: ${frame.field}`);
  console.log(`Encoded Node: ${frame.encodedNode}`);
  console.log(`Carrier: ${frame.carrier}`);
  console.log(`Signal Clarity: ${frame.clarity}%   [register ${frame.register}]`);
  console.log(`\n⦿ PROTOCOL BEGIN\n`);
  lines.forEach(l => console.log("  " + l));
  console.log(`\n⦿ PROTOCOL COMPLETE`);
  console.log(`— ${frame.encodedNode}   Channel status: ${frame.status}`);
}

async function main() {
  const today = frameFor();
  render(today, await generate(today));

  // Same day, clarity forced down, to expose the register shift.
  const low = { ...today, clarity: 43.2, status: statusFor(43.2), register: registerFor(43.2) };
  render(low, await generate(low));
}

main().catch(e => {
  console.error("PROBE FAILED:", e?.message || e);
  process.exit(1);
});
