import { createPortal } from "react-dom";
import { AnimatePresence, motion } from "framer-motion";

/**
 * ArcanaSignalTransition
 *
 * Full-screen "changing frequency on an old radio / TV" overlay used when the
 * user tunes from the Home signal onto the ARKANA frequency:
 *
 *   Home signal -> signal loss -> static noise -> recalibration -> ARKANA lock.
 *
 * Pure CSS/SVG (feTurbulence grain + scanlines + horizontal tear + gold
 * flicker). No video asset required. Framer Motion handles the fade in/out so
 * the overlay never hard-cuts. Rendered through a portal on <body> so it sits
 * above the fixed header and every page layer.
 */
export default function ArcanaSignalTransition({ active }: { active: boolean }) {
  if (typeof document === "undefined") return null;

  return createPortal(
    <AnimatePresence>
      {active && (
        <motion.div
          className="asig-overlay"
          aria-hidden="true"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.42, ease: "easeOut" }}
        >
          {/* Grain / static field generated by SVG turbulence */}
          <svg className="asig-noise" width="100%" height="100%">
            <filter id="asig-static-filter">
              <feTurbulence
                type="fractalNoise"
                baseFrequency="0.9"
                numOctaves="2"
                stitchTiles="stitch"
              />
              <feColorMatrix type="saturate" values="0" />
            </filter>
            <rect
              width="100%"
              height="100%"
              filter="url(#asig-static-filter)"
            />
          </svg>

          {/* Scanlines */}
          <div className="asig-scanlines" />

          {/* Horizontal signal tearing band */}
          <div className="asig-tear" />

          {/* Subtle gold flicker — the carrier trying to lock */}
          <div className="asig-gold" />

          {/* Frequency-lock readout */}
          <div className="asig-lock">
            <span className="asig-lock__line" />
            <span className="asig-lock__label">RECALIBRATING SIGNAL</span>
            <span className="asig-lock__line" />
          </div>

          <style>{`
            .asig-overlay {
              position: fixed;
              inset: 0;
              z-index: 9999;
              background: #050505;
              overflow: hidden;
              pointer-events: all;
            }

            .asig-noise {
              position: absolute;
              inset: 0;
              width: 100%;
              height: 100%;
              opacity: 0.55;
              mix-blend-mode: screen;
              animation: asig-flicker 0.18s steps(2) infinite;
            }

            .asig-scanlines {
              position: absolute;
              inset: 0;
              background: repeating-linear-gradient(
                to bottom,
                rgba(0, 0, 0, 0) 0px,
                rgba(0, 0, 0, 0) 2px,
                rgba(0, 0, 0, 0.55) 3px,
                rgba(0, 0, 0, 0.55) 4px
              );
              animation: asig-scan 7s linear infinite;
              opacity: 0.5;
            }

            .asig-tear {
              position: absolute;
              left: -10%;
              right: -10%;
              height: 14%;
              top: 30%;
              background: linear-gradient(
                to bottom,
                rgba(216, 181, 109, 0) 0%,
                rgba(216, 181, 109, 0.14) 45%,
                rgba(255, 255, 255, 0.22) 50%,
                rgba(216, 181, 109, 0.14) 55%,
                rgba(216, 181, 109, 0) 100%
              );
              filter: blur(0.5px);
              animation: asig-tear-move 1.2s ease-in-out infinite;
            }

            .asig-gold {
              position: absolute;
              inset: 0;
              background: radial-gradient(
                circle at 50% 50%,
                rgba(246, 176, 94, 0.16) 0%,
                rgba(216, 181, 109, 0.06) 35%,
                rgba(5, 5, 5, 0) 70%
              );
              animation: asig-gold-flicker 0.9s ease-in-out infinite;
            }

            .asig-lock {
              position: absolute;
              left: 50%;
              top: 50%;
              transform: translate(-50%, -50%);
              display: flex;
              align-items: center;
              gap: 14px;
              opacity: 0;
              animation: asig-lock-in 1.3s ease-out forwards;
            }

            .asig-lock__line {
              display: block;
              width: clamp(40px, 8vw, 90px);
              height: 1px;
              background: linear-gradient(
                to right,
                rgba(216, 181, 109, 0),
                rgba(216, 181, 109, 0.7),
                rgba(216, 181, 109, 0)
              );
            }

            .asig-lock__label {
              font-family: var(--font-ritual, ui-monospace, monospace);
              font-size: 10px;
              letter-spacing: 0.32em;
              color: #d8b56d;
              text-shadow: 0 0 18px rgba(246, 176, 94, 0.55);
              white-space: nowrap;
            }

            @keyframes asig-flicker {
              0% { opacity: 0.5; transform: translateX(0); }
              50% { opacity: 0.62; transform: translateX(-1%); }
              100% { opacity: 0.48; transform: translateX(1%); }
            }

            @keyframes asig-scan {
              from { background-position-y: 0; }
              to { background-position-y: 100px; }
            }

            @keyframes asig-tear-move {
              0% { top: 12%; opacity: 0.2; }
              35% { top: 58%; opacity: 0.9; }
              70% { top: 24%; opacity: 0.4; }
              100% { top: 76%; opacity: 0.15; }
            }

            @keyframes asig-gold-flicker {
              0%, 100% { opacity: 0.35; }
              40% { opacity: 0.85; }
              60% { opacity: 0.2; }
            }

            @keyframes asig-lock-in {
              0% { opacity: 0; letter-spacing: 0.6em; }
              60% { opacity: 0; }
              80% { opacity: 0.4; letter-spacing: 0.32em; }
              100% { opacity: 0.85; letter-spacing: 0.32em; }
            }

            @media (prefers-reduced-motion: reduce) {
              .asig-noise,
              .asig-scanlines,
              .asig-tear,
              .asig-gold,
              .asig-lock {
                animation: none;
              }
            }
          `}</style>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );
}
